plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = property('mod_version')
group = property('mod_group_id')

base {
    archivesName = property('mod_id')
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = property('neoforge_version')

    parchment {
        mappingsVersion = '2024.11.17'
        minecraftVersion = '1.21.1'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', property('mod_id')
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', property('mod_id')
        }
    }

    mods {
        "${property('mod_id')}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.46.1.0'
    jarJar 'org.xerial:sqlite-jdbc:3.46.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

sourceSets {
    test {
        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
